wip: fails to compile because borrow checker is not happy
error[E0502]: cannot borrow  as mutable because it is also borrowed as immutable
   --> src/app.rs:584:51
    |
584 |         state.prompt_widget().render(prompt, buf, &mut state.prompt);
    |         -----                 ------              ^^^^^^^^^^^^^^^^^ mutable borrow occurs here
    |         |                     |
    |         |                     immutable borrow later used by call
    |         immutable borrow occurs here